### ISSUE TITLE
[Audio]: Mining Inc Audios [More then just one]

### ISSUE THREAD

**Issue by Geruchsneutral44** [retro-dev-rblx/Music#100]
### Check if this audio is already added to RetroStudio.

- [X] The audio is not already in game.

### Is this for the main-menu playlist?

- [ ] Add to main-menu playlist.

### Is this song from an old Roblox era or a sound effect?

- [X] This song is from old Roblox or is a sound effect.

### A link to the audio on Roblox

https://www.roblox.com/library/12823128891,  https://www.roblox.com/library/12823127347,  https://www.roblox.com/library/12823126033,  https://www.roblox.com/library/12823123146,  https://www.roblox.com/library/12823121908,  https://www.roblox.com/library/12823120328

### A link to the audio file to download.

https://drive.google.com/drive/folders/1USR3Chll959is_xrxi6UlZk_j_VPKZbt?usp=sharing

### Notes

All these sounds are required to finish our Mining Inc game.

**Comment by Cristiano100** [comment]
"Generator Sound": [
      "rbxassetid://12909748052"
    ],
    "Outdoor Factory Ambience": [
      "rbxassetid://12909746395"
    ],
    "Large Engine Sound": [
      "rbxassetid://12909749938"
    ],
    "Large Engine Sound 2": [
      "rbxassetid://12909744299"
    ],
    "Hydro Turbine": [
      "rbxassetid://12909751263"
    ],
    "Cave Ambience": [
      "rbxassetid://12909752881"
    ],
