### ISSUE TITLE
[Audio]: Bass 5

### ISSUE THREAD

**Issue by GithubVibin** [retro-dev-rblx/Music#152]
### Check if this audio is already added to RetroStudio.

- [X] The audio is not already in game.

### Is this for the main-menu playlist?

- [ ] Add to main-menu playlist.

### Is this song from an old Roblox era or a sound effect?

- [X] This song is from old Roblox or is a sound effect.

### A link to the audio on Roblox

https://www.roblox.com/library/181644155/Bass-5

### A link to the audio file to download.

https://cdn.discordapp.com/attachments/811050426622541824/1183599800055255100/181644155.mp3?ex=6588ec36&is=65767736&hm=eec2be19822e787c6709c4f3e1517725a655d845696481f9137315cb91f275af&

**Comment by Cristiano100** [comment]
rbxassetid://15750707229
