### ISSUE TITLE
[Audio]: MLG Sound Effect

### ISSUE THREAD

**Issue by thom463s** [retro-dev-rblx/Music#154]
### Check if this audio is already added to RetroStudio.

- [X] The audio is not already in game.

### Is this for the main-menu playlist?

- [ ] Add to main-menu playlist.

### Is this song from an old Roblox era or a sound effect?

- [X] This song is from old Roblox or is a sound effect.

### A link to the audio on Roblox

https://www.roblox.com/library/15613471996/MLG

### A link to the audio file to download.

https://www.mediafire.com/file/ovnhdjlxvyd6tjo/MLG.mp3/file

### Notes

Gonna use this sound for a Mtn Dew gear in Murdered. Pretty sure this could be considered a sound effect or "old roblox" because MLG sounds date way back to like 2014.

**Comment by GithubVibin** [comment]
0 retros

**Comment by Cristiano100** [comment]
rbxassetid://15750706950
