### ISSUE TITLE
[Audio]: More Kevin MacLeod music. (Please read notes!

### ISSUE THREAD

**Issue by cubers93** [retro-dev-rblx/Music#287]
### Check if this audio is already added to RetroStudio.

- [X] The audio is not already in game.

### Is this for the main-menu playlist?

- [ ] Add to main-menu playlist.

### Is this song from an old Roblox era or a sound effect?

- [X] This song is from old Roblox or is a sound effect.

### A link to the audio on Roblox

Multiple audios, check download link.

### A link to the audio file to download.

https://www.mediafire.com/file/5d2kzb1kvkv2tn2/KevinMacleod.zip/file

### Notes

There is currently 3 Kevin Macleod songs in the library, and they are all with a single theme: (Intense/horror).
I have selected some songs that have been used alot, and some that are recognized from specific games on Roblox
I have also used MediaFire to upload these MP3s of the songs, since I don't know any good platform for uploading files. And Discord won't really work because it deletes files after 24 hours. And if you don't trust the .zip file, i can understand. So that's why I'll put a direct download to the MP3s and why they are mostly known for below:
https://www.mediafire.com/file/8mn35r47b4nozn2/Decisions.mp3/file (Flood Escape Classic)
https://www.mediafire.com/file/m0wsi95nlf24mzl/Fluffing_a_Duck.mp3/file (Widely used in general.)
https://www.mediafire.com/file/ovak9grtpmg0ava/Hitman.mp3/file (Widely used in general. Possibly BFDI)
https://www.mediafire.com/file/ik74fqfv9vzrjgv/Local_Forecast.mp3/file (The Normal Elevator)
https://www.mediafire.com/file/k3nrorf0z4t9rl3/Meatball_Parade.mp3/file (Widely used in general.)
https://www.mediafire.com/file/ehjys3ixptbei6x/Mistake_the_Getaway.mp3/file (Widely used in general. BFDI)
https://www.mediafire.com/file/fkf8a3dal1x1en8/Pixelland.mp3/file (Widely used in general.)
https://www.mediafire.com/file/vzcbs0he7owrqpn/Rocket.mp3/file (Flood Escape Classic)
https://www.mediafire.com/file/n31s8jwfzgm8ugt/Scheming_Weasel_%2528faster_Version%2529.mp3/file (Widely used in general.)
https://www.mediafire.com/file/z7usnd72eaocwo1/Sneaky_Snitch.mp3/file (Widely used in general)
https://www.mediafire.com/file/oeryahipn7xjsoo/Spazzmatica_Polka.mp3/file (Widely used in general)
https://www.mediafire.com/file/i3y0oc30vep2ah7/The_House_of_Leaves.mp3/file (Pinewood Builders Computer Core)
https://www.mediafire.com/file/pr25a32hf2j32vj/Who_Likes_to_Party.mp3/file (PARTY.exe)

**Comment by Parrot88124** [comment]
added (im not a mod but heres the link to the message)
https://discord.com/channels/645632117455323136/724470057886941184/1258567008543309865

**Comment by cubers93** [comment]
well, it has been added. thanks, devs!
