### ISSUE TITLE
[Audio]: Never Gonna Give you up [MIDI]

### ISSUE THREAD

**Issue by cooldude1067** [retro-dev-rblx/Music#33]
### Check if this audio is already added to RetroStudio.

- [X] The audio is not already in game.

### Is this for the main-menu playlist?

- [X] Add to main-menu playlist.

### Is this song from an old Roblox era or a sound effect?

- [X] This song is from old Roblox or is a sound effect.

### A link to the audio on Roblox

https://www.roblox.com/library/9894525501/Never-Gonna-Give-You-Up-Roblox-Edition

### A link to the audio file to download.

https://drive.google.com/file/d/1S0VIcD5NGKD-_s8ZXfFCKhefclxIkWk1/view?usp=sharing

### Notes

Original song used by many players from 2008-2014.
Generated using Gamehero's classic midi player.
Copyright Detection doesn't work on midi :)

**Comment by gitcrazier** [comment]
Wouldn't this be considered a custom rendition? The Rick Roll that I remember was uploaded by clockwork, and existed until around 2014 (like you said) in which no Wayback Machine archives remain other than YouTube videos that played it.

**Comment by cooldude1067** [comment]
I suppose you're right, though personally I prefer it to pitch-shifting or slowing down the original to avoid copyright.

**Comment by retrocyanmobile** [comment]
i'd suggest pitching it down, since it's likely retro dev won't notice it's slowed sown. and if that happened, there's no speed setting so..yeah.

or you can just clarify it in the title 📦:P

**Comment by Cristiano100** [comment]
Menu Music should also be special. The box should have been left unchecked

**Comment by RetroCyan** [comment]
> If it’s pitch shifted we are unable to add it!

Why so?
