### ISSUE TITLE
[Audio]: Geppetto Soundtrack - And Son

### ISSUE THREAD

**Issue by Stickpuppet** [retro-dev-rblx/Music#34]
### Check if this audio is already added to RetroStudio.

- [X] The audio is not already in game.

### Is this for the main-menu playlist?

- [X] Add to main-menu playlist.

### Is this song from an old Roblox era or a sound effect?

- [X] This song is from old Roblox or is a sound effect.

### A link to the audio on Roblox

https://www.roblox.com/library/7577305972/Geppetto-Soundtrack-And-Son

### A link to the audio file to download.

https://drive.google.com/file/d/1EncBe1cMVZQZHZDzVsztUXxf1e5QNLol/view?usp=sharing

### Notes

Part of the Geppetto soundtrack, if you do not add I will cry and scream

**Comment by Cristiano100** [comment]
This is not being added to the main menu
