### ISSUE TITLE
[Audio]: Super Mario USA: Overworld

### ISSUE THREAD

**Issue by PiSquaredx3** [retro-dev-rblx/Music#39]
### Check if this audio is already added to RetroStudio.

- [X] The audio is not already in game.

### Is this for the main-menu playlist?

- [X] Add to main-menu playlist.

### Is this song from an old Roblox era or a sound effect?

- [X] This song is from old Roblox or is a sound effect.

### A link to the audio on Roblox

https://www.roblox.com/library/10069359253/Mario-USA-Overworld

### A link to the audio file to download.

https://vgmsite.com/soundtracks/super-mario-bros-2/grtazrcgrf/03%20Overworld.mp3

### Notes

I feel like this song could work very well in social hangouts or role playing games.

**Comment by Cristiano100** [comment]
In your notes it says it would work in games, so please don’t check the main menu music box

**Comment by PiSquaredx3** [comment]
> 

Sorry, for some reason it doesn't let you post unless you do.
