### ISSUE TITLE
[Audio]: Bashy - Classic Days

### ISSUE THREAD

**Issue by RetroCyan** [retro-dev-rblx/Music#45]
### Check if this audio is already added to RetroStudio.

- [X] The audio is not already in game.

### Is this for the main-menu playlist?

- [ ] Add to main-menu playlist.

### Is this song from an old Roblox era or a sound effect?

- [X] This song is from old Roblox or is a sound effect.

### A link to the audio on Roblox

https://www.roblox.com/library/10106354475/Bashy-Classic-Days

### A link to the audio file to download.

https://drive.google.com/file/d/1Gvhqobyi3vnmI0-llCkUn_K-zI4yvz8s/view?usp=sharing

**Comment by Cristiano100** [comment]
Audio download does not match roblox audio
