### ISSUE TITLE
[Audio]: Blackhawk Rescue Mission 2 Loadout OST

### ISSUE THREAD

**Issue by PanzergrenadierPzG** [retro-dev-rblx/Music#52]
### Check if this audio is already added to RetroStudio.

- [X] The audio is not already in game.

### Is this for the main-menu playlist?

- [ ] Add to main-menu playlist.

### Is this song from an old Roblox era or a sound effect?

- [X] This song is from old Roblox or is a sound effect.

### A link to the audio on Roblox

Due to the Roblox audio update, I was unable to find the link to this.

### A link to the audio file to download.

https://cdn.discordapp.com/attachments/991220468587692042/996317435470807080/brm2_loadout.mp3

### Notes

This was used in Blackhawk Rescue Mission 2. BRM2 was created in 2011, so it is from old Roblox.
I was unable to find this audio on the Roblox website because of the audio update which made all audios private.

**Comment by RetroCyan** [comment]
ARE WE EVER GONNA GET A FUCKING AUDIO UPDATE?! IT'S BEEN TWO MONTHS!!

**Comment by Cristiano100** [comment]
No link to roblox uploaded-audio
