### ISSUE TITLE
[Audio]:Club Penguin Halloween Party 2008

### ISSUE THREAD

**Issue by Someoneslamp** [retro-dev-rblx/Music#57]
### Check if this audio is already added to RetroStudio.

- [X] The audio is not already in game.

### Is this for the main-menu playlist?

- [ ] Add to main-menu playlist.

### Is this song from an old Roblox era or a sound effect?

- [X] This song is from old Roblox or is a sound effect.

### A link to the audio on Roblox

https://www.roblox.com/library/836233088/

### A link to the audio file to download.

https://downloads.khinsider.com/game-soundtracks/album/club-penguin-original-soundtrack/14.%2520Halloween%2520Party%25202008%2520Outdoors%2520Theme.mp3

### Notes

This song is from the 2008 club penguin event, but I'm not too sure if that reaches the criteria of being classified as "Old Roblox Era" please let me know if this must be a roblox song.

**Comment by RetroCyan** [comment]
This was used in the 2021 october event, so i hope it's added.
