### ISSUE TITLE
[Audio]: Club Penguin Halloween 2008 - In The Halloween Storm

### ISSUE THREAD

**Issue by 3gc4Awesomeness** [retro-dev-rblx/Music#58]
### Check if this audio is already added to RetroStudio.

- [X] The audio is not already in game.

### Is this for the main-menu playlist?

- [X] Add to main-menu playlist.

### Is this song from an old Roblox era or a sound effect?

- [ ] This song is from old Roblox or is a sound effect.

### A link to the audio on Roblox

https://www.roblox.com/library/836233088/

### A link to the audio file to download.

https://cdn.discordapp.com/attachments/708571230793367576/1021766938080321627/FTOsOkQG.mp3

### Notes

i need one for my game

**Comment by RetroCyan** [comment]
me waiting for retro dev to add more songs

**Comment by Cristiano100** [comment]
Dead download
