### ISSUE TITLE
[Audio]: MEGALOVANIA

### ISSUE THREAD

**Issue by gitcrazier** [retro-dev-rblx/Music#6]
### Check if this audio is already added to RetroStudio.

- [X] The audio is not already in game.

### Is this for the main-menu playlist?

- [X] Add to main-menu playlist.

### Is this song from an old Roblox era or a sound effect?

- [X] This song is from old Roblox or is a sound effect.

### A link to the audio on Roblox

https://www.roblox.com/library/9744923045/

### A link to the audio file to download.

https://static.wikia.nocookie.net/supercubecavern/images/4/4e/MEGALOVANIA.ogg/revision/latest?cb=20220527150438&format=original

### Notes

**MEGALOVANIA** is from "Old ROBLOX" if you consider Late 2015 to be so. Although, I believe **Undertale** was in development since sometime in _2012_, so this song has probably existed since before the release version (obviously it would've, since I doubt Toby Fox would've made this song at the very last minute).

Whether or not you would want to add it to the main menu playlist is entirely up to you. The song is really catchy, and it's one of my favorites. (About a year ago, I believe Tyler told me that Undertale was one of his favorite games. (〜￣▽￣)〜)

I could be wrong though, but that's what I seem to recall.

I just want to be able to play it in **RETROSTUDIO**, and allow for others to use it as well. Whether or not ROBLOX will let you though, is another thing. I've only seen _maybe_ one or two uploads of the original version of this song when I've looked through the Library in the past. The rest of them have been **meme** and **orchestral** covers.

Also, it looks like I can just attach files to the **Notes**. Would it be alright if I just did that from now on? I don't really want to upload to a **FANDOM** Wiki every time, since it will end up cluttering the upload logs after a while.

Thanks for reading this! I hope things get resolved for RETROSTUDIO soon, so we can go back to playing it again.

**P.S.** It appears most of the audio mentioned in **Music.json** don't work in RETROBLOX. I _believe_ the only exceptions to this are **The Great Strategy**, **M.U.L.E**, **Outrun the Nightmare**, **The Entertainer**, and **Raining Tacos**. The rest of them just throw an error in the **Dev Console** saying that the sound data couldn't be downloaded.

**Comment by Cristiano100** [comment]
Upload the audio to roblox first

**Comment by gitcrazier** [comment]
> Upload the audio to roblox first

Okay. I can do that, but wouldn't I need to have edit access to the Universe(s) in order for you to add it? I'm not entirely sure how this works, so if you could explain it a bit more to me I would appreciate it.

**Comment by Cristiano100** [comment]
ok so how this works is you follow the form and upload the audio to roblox.

**Comment by gitcrazier** [comment]
> ok so how this works is you follow the form and upload the audio to roblox.

Sounds simple.

I'll do that, then.

**Comment by gitcrazier** [comment]
Done! I apologize if I gave you trouble. This is the first Issue I've made.

Thanks in advance!

**Comment by Cristiano100** [comment]
you dont need anything in notes btw
