### ISSUE TITLE
[Audio]: Super Mario Sunshine. "Vs. Boss"

### ISSUE THREAD

**Issue by Someoneslamp** [retro-dev-rblx/Music#78]
### Check if this audio is already added to RetroStudio.

- [x] The audio is not already in game.

### Is this for the main-menu playlist?

- [ ] Add to main-menu playlist.

### Is this song from an old Roblox era or a sound effect?

- [X] This song is from old Roblox or is a sound effect.

### A link to the audio on Roblox

https://www.roblox.com/library/167359361/Super-Mario-Sunshine-Boss-Battle?Category=Audio&SortType=Relevance&SortAggregation=AllTime&SearchKeyword=old+windows+error&CreatorId=0&Page=1&Position=7&SearchId=e2fc8e49-c686-493a-b6b8-7e1993a90e28

### A link to the audio file to download.

https://downloads.khinsider.com/game-soundtracks/album/super-mario-sunshine-game-rip/20.%2520Vs.%2520Boss.mp3

**Comment by Cristiano100** [comment]
12909931229
