### ISSUE TITLE
[Audio]: Kevin Macleod - Movement Proposition

### ISSUE THREAD

**Issue by KyndaKold** [retro-dev-rblx/Music#79]
### Check if this audio is already added to RetroStudio.

- [X] The audio is not already in game.

### Is this for the main-menu playlist?

- [x] Add to main-menu playlist.

### Is this song from an old Roblox era or a sound effect?

- [X] This song is from old Roblox or is a sound effect.

### A link to the audio on Roblox

https://www.roblox.com/library/12216709656/

### A link to the audio file to download.

https://incompetech.com/music/royalty-free/mp3-royaltyfree/Movement%20Proposition.mp3

### Notes

This is the boss music from Egg Hunt 2013.

**Comment by Cristiano100** [comment]
12909903896
