### ISSUE TITLE
[Audio]: Kevin Macleod - Darkest Child

### ISSUE THREAD

**Issue by KyndaKold** [retro-dev-rblx/Music#80]
### Check if this audio is already added to RetroStudio.

- [X] The audio is not already in game.

### Is this for the main-menu playlist?

- [x] Add to main-menu playlist.

### Is this song from an old Roblox era or a sound effect?

- [X] This song is from old Roblox or is a sound effect.

### A link to the audio on Roblox

https://www.roblox.com/library/12216692811/

### A link to the audio file to download.

https://incompetech.com/music/royalty-free/mp3-royaltyfree/Darkest%20Child.mp3

### Notes

This is the background music in Egg Hunt 2013. Also, I accidentally uploaded the quicker version A to ROBLOX. It's the same song, just slightly faster, so the ROBLOX link and the file aren't the same.

**Comment by Cristiano100** [comment]
12909901062
