### ISSUE TITLE
[Audio]: TF2 Votekick Sound Effects

### ISSUE THREAD

**Issue by Greenbulb** [retro-dev-rblx/Music#82]
### Check if this audio is already added to RetroStudio.

- [X] The audio is not already in game.

### Is this for the main-menu playlist?

- [ ] Add to main-menu playlist.

### Is this song from an old Roblox era or a sound effect?

- [X] This song is from old Roblox or is a sound effect.

### A link to the audio on Roblox

https://www.roblox.com/library/12392326543/TF2-Vote-Called

### A link to the audio file to download.

https://drive.google.com/file/d/1Kx59kqL7lw84qASgGGNOuG8lM9hMC1sm/view?usp=share_link

### Notes

I was going to put each sound effect for a TF2 vote in seperate issues, but decided to put them all here for convenience.

**Vote Called** (linked above)
https://www.roblox.com/library/12392326543/TF2-Vote-Called
https://drive.google.com/file/d/1Kx59kqL7lw84qASgGGNOuG8lM9hMC1sm/view?usp=share_link

**Yes Vote**
https://www.roblox.com/library/12392361233/TF2-Voted-Yes
https://drive.google.com/file/d/1ujb2dMod2ZaygTfkn8vdwZb7gqeXse8v/view?usp=share_link

**No Vote**
https://www.roblox.com/library/12392373688/TF2-Voted-No
https://drive.google.com/file/d/1T3ObSrECodWyGFT9PjI3qS-tIb5cDQou/view?usp=share_link

**Vote Successful**
https://www.roblox.com/library/12392388995/TF2-Vote-Successful
https://drive.google.com/file/d/1xsus0p3wixjfBIzq2j4OcOwhQuOHei9a/view?usp=share_link

**Vote Failed**
https://www.roblox.com/library/12392407843/TF2-Vote-Failed
https://drive.google.com/file/d/1zxiz84Z5RR3w--l_lgCTdxqUauyzvFpy/view?usp=share_link

**Comment by Cristiano100** [comment]
"Vote Failure": [
      "rbxassetid://12909855052"
    ],
    "Vote No": [
      "rbxassetid://12909856411"
    ],
    "Vote Yes": [
      "rbxassetid://12909858157"
    ],
    "Vote Success": [
      "rbxassetid://12909857240"
    ],
    "Vote Started": [
      "rbxassetid://12909861156"
    ]
