### ISSUE TITLE
[Audio]: S4 League - Come On (Tunnel)

### ISSUE THREAD

**Issue by Reposits** [retro-dev-rblx/Music#98]
### Check if this audio is already added to RetroStudio.

- [X] The audio is not already in game.

### Is this for the main-menu playlist?

- [ ] Add to main-menu playlist.

### Is this song from an old Roblox era or a sound effect?

- [X] This song is from old Roblox or is a sound effect.

### A link to the audio on Roblox

https://www.roblox.com/library/12676956072/New-audio

### A link to the audio file to download.

https://drive.google.com/file/d/1wx4kYBE0LspbYSvbW_HVaDO4a2K6VCJT/view?usp=sharing

### Notes

This song has been used in old Simon Says, Mega Wave, and The Stalker. It was uploaded by a roblox admin way back in the days

**Comment by RetroCyan** [comment]
OMG HOW DID YOU GET IT PAST THE SYSTEM?? TEACH ME SO I CAN UPLOAD SOME SONGS PLEASE :D

**Comment by Reposits** [comment]
> PAST

Lol i just uploaded it without modifications and it worked. The game has also been shut down 2 years ago permanently. Dw if you are that worried then you can rename the audio to something unrelated and do it on a throwaway :D

**Comment by Cristiano100** [comment]
google drive link is closed
