### ISSUE TITLE
[Audio]: Sparta Remix

### ISSUE THREAD

**Issue by HappyGuy9080** [retro-dev-rblx/Music#99]
### Check if this audio is already added to RetroStudio.

- [X] The audio is not already in game.

### Is this for the main-menu playlist?

- [X] Add to main-menu playlist.

### Is this song from an old Roblox era or a sound effect?

- [X] This song is from old Roblox or is a sound effect.

### A link to the audio on Roblox

https://www.roblox.com/library/12797347797/Audio-Sparta-Remix-Extended-Instrumental-version

### A link to the audio file to download.

https://mega.nz/file/lqJGRBhY#BoaVJxCmhEJdOFo6WPdwvNtHGzkzTvCXzIs0CUKUQPg

### Notes

This song is very nostalgic to me. I remember playing an obby game in which when completing it this song would play. It would be very nice if it was added.

**Comment by Cristiano100** [comment]
12909812780
